### ISSUE TITLE
Support for SuSE distributions?

### ISSUE THREAD

**Issue by tobias-klein** [electron-userland/electron-installer-redhat#130]
I've been trying to install a rpm generated by electron-installer-redhat on OpenSuse 42.3. It didn't work, because some of the standard dependencies of the package were not found. Is SuSE supported in general or are there plans to support it?

**Comment by fcastilloec** [comment]
Could you be a more specific and show what are the dependencies failing to be installed? Also, are you using the latest release of this module (v2.0.0)?

**Comment by tobias-klein** [comment]
When installing the RPM I get the following message from Yast:

```
#### YaST2 conflicts list - generated 2019-06-16 17:33:02 ####

nothing provides (kde-cli-tools or kde-runtime or trash-cli or glib2 or gvfs-client) needed by ezra-project-0.8.1-1.x86_64
```

**Comment by malept** [comment]
Well, that's confusing, because I did a cursory search and [`glib2`](https://software.opensuse.org/package/glib2) exists in openSUSE. What version of RPM do you have installed?

That being said, apparently `kde-cli-tools` is called [`kde-cli-tools5` in openSUSE](https://software.opensuse.org/package/kde-cli-tools5).

**Comment by tobias-klein** [comment]
On the system I'm installing the package it's RPM version 4.11.2 and on the system where I'm generating the package (a Docker image) it's 4.14.2.1.

**Comment by malept** [comment]
I suspect the reason why it doesn't like the trash dependency line is because it requires RPM 4.13.0.

**Comment by malept** [comment]
According to https://rpm.org/timeline.html, 4.13.0 was released almost 3 years ago.

**Comment by tobias-klein** [comment]
Thanks for the additional hints. I'm not so familiar with different Suse releases and the package versions available for them. If a newer RPM is required then I'll give another newer Suse release a try. I've been using OpenSuse Leap 42.3 (released ~2 years ago). Imho, it's sometimes valuable to support older releases, because people don't always use the latest stuff. Thanks for your help, I appreciate it!

**Comment by fcastilloec** [comment]
@tobias-klein this tool supports old and new versions. All this fine tuning has to be done by the user, by using a newer rpm version when building you are excluding releases with older versions.

If you're not using `shell.moveItemToTrash` method from electron, it's better to build the installer on a Docker image with an older rpm version (< 4.13), this will make sure that it will work on all rpm versions.
If you do use that method, or can't build on an older system, you can add a dependency to rpm with [`options.requires`](https://github.com/electron-userland/electron-installer-redhat#optionsrequires) on your config file, like this: `[rpm >= 4.13]`. That'll make sure your installer will work only on newer systems.

**Comment by tobias-klein** [comment]
This issue is not closed from my perspective.

I just generated an RPM on OpenSuse Leap 15.1 (released in May 2019) and electron-installer-redhat (2.0.0) still seems to generate dependencies that are not compatible with that Suse distribution.

The following dependencies are not found when installing the generated package on OpenSuse Leap 15.1:
- libXtst (package name on OpenSuse Leap: libXtst**6**)
- libnotify (package name on OpenSuse Leap: libnotify**4**)
- libuuid (package name on OpenSuse Leap: libuuid**1**)
- nss (package name on OpenSuse Leap: (???)

I'd appreciate if you could re-open this ticket and provide a fix!

**Comment by malept** [comment]
Feel free to provide a patch, as you seem to be more knowledgeable about OpenSuse. `nss` is [Network Security Services](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS).

**Comment by tobias-klein** [comment]
I fixed this by making a change in electron-installer-common as well as electron-installer-redhat (see the two pull requests referenced above). The changes were tested successfully on OpenSuse Leap 15.1.
