### ISSUE TITLE
rpmbuild strips binaries by default (fix included)

### ISSUE THREAD

**Issue by markibanez** [electron-userland/electron-installer-redhat#159]
This isn't really a problem with electron-installer-redhat. However, when the package also has other executable binaries, by default rpmbuild "strips" them which in effect corrupts the files. I discovered this while testing my app and seeing the functionality broken, and indeed the executable binaries were way smaller than they should be.

The fix is to add `%global __os_install_post %{nil}` in the first line of the spec file. I'm not sure if there's a configuration to customize the spec file from ci or api, but I could not find one in the source code. So  for the meantime, I manually added that line to `resources/spec.ejs`. 

I found the fix in the following urls 
https://stackoverflow.com/questions/33828210/rpmbuild-with-executable-files
https://unix.stackexchange.com/questions/281854/binary-file-got-corrupted-after-packaging

Would you consider adding this fix by default?

**Comment by fcastilloec** [comment]
Thanks for reporting this and even better for also including a fix!
I've never encountered this problem and I'm not very familiar with it. I'm not sure if we want to set this as the default, there are only very specific cases where this is needed. We could add an option to disable compressing (and binary stripping as a result of it).

I think a better approach would be to leave `resources/spec.ejs` as is and instead add the following line to `~/.rpmmacros` or `/etc/rpm/macros`: `%__os_install_post %{nil}`

Currently, we have neglected to fix #62 which makes my suggestion not useful but in the coming days, I'll try to push a fix for that bug. This way, not only your case buy anybody else that requires specific macros can easily add them.

**Comment by markibanez** [comment]
Yep adding that option would be great. At least it'll avoid some headscratching for others down the road. Thanks.
