### ISSUE TITLE
electron-installer-redhat overwrites existing ~/.rpmmacros file

### ISSUE THREAD

**Issue by jrobeson** [electron-userland/electron-installer-redhat#62]
**What version of `electron-installer-redhat` are you using?**
0.3.1
**What version of `node` and `npm` are you using?**
7.8.0, 4.2.0
**What operating system are you using?**
Fedora 25
**Can you compile the [example app](https://github.com/unindented/electron-installer-redhat/tree/master/example) successfully?**
yes
**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/unindented/electron-installer-redhat.git
$ cd electron-installer-redhat/example
$ DEBUG='electron-installer-redhat' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-redhat`.**
no config, defaults as per electron-forge
**What did you expect to happen?**

I expected by `~/.rpmmacros file to not be overwritten

**What actually happened?**
my `~/.rpmmacros` file was overrwritten with:
```
%_topdir /tmp/electron-11727-17936-jxpyxa.af9a4i/app_0.0.1_x86_64
```

It might be a better idea to  use  `rpmbuild`s `--macros=<FILE>` instead of replacing the `~/.rpmmacros` file.

**Comment by unindented** [comment]
Would you be able to create a PR for this issue?

**Comment by jrobeson** [comment]
I'm taking back my idea of ``--macros=<FILE>` as that means we'd have to store it local to the project. Why not just pass `-D _topdir` instead?
