### ISSUE TITLE
Feature Request: Support for pre, post, preun, postun scripts

### ISSUE THREAD

**Issue by webD97** [electron-userland/electron-installer-redhat#78]
This package is very useful for building RPMs and works very well so far.

I'd like to see support for adding various scriptlets to the spec file, for example:
- pre (before installation)
- post (after installation)
- preun (before uninstallation)
- postun (after uninstallation)

In my project, I need to execute some additional commands after installation and before uninstallation, so this feature would help me keeping a clean package structure.

Thanks in advance :)

**Comment by fcastilloec** [comment]
@webD97 Sorry for taking so long, but this has been implemented on the master branch (not released yet) if you want to try it and report any bugs

**Comment by webD97** [comment]
That's great news! Unfortunately I do not have the time right now to test it because I am busy with my studies...
