### ISSUE TITLE
Enhancement: Add the ability to use a desktop template file

### ISSUE THREAD

**Issue by cruzerld** [electron-userland/electron-installer-redhat#85]
I saw that electron-installer-debian has the ability to use a desktop.ejs template for the .desktop file. I'd like to do the same thing with this package.

Should I attempt to port the code over from there to here? https://github.com/unindented/electron-installer-debian/pull/98

Thanks!

**Comment by fcastilloec** [comment]
Sure! feel free to open a PR for it. Make sure you also port the test for it

**Comment by malept** [comment]
Yeah, sorry about that. I hadn't had time to sync this module with the changes we've made to `electron-installer-debian`.
